# Generated by Django 4.1.13 on 2024-07-03 08:00

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mongodbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Vehicle_No', models.CharField(max_length=20)),
                ('O_name', models.CharField(max_length=100)),
                ('Vehicle_Class', models.CharField(max_length=50)),
                ('Chassis_No', models.CharField(max_length=50)),
                ('Engine_No', models.IntegerField()),
                ('Vehicle_Model', models.CharField(max_length=100)),
                ('Violation_Date', models.DateField()),
                ('Challan_Date', models.DateField()),
                ('Challan_No', models.CharField(max_length=20)),
                ('Place_Of_Violation', models.CharField(max_length=100)),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Driving_license_No', models.CharField(max_length=20)),
                ('Driver_Contact_No', models.CharField(max_length=15)),
                ('Driver_FatherName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VehicleRecord',
            },
        ),
    ]
