# Generated by Django 5.0.6 on 2024-07-10 17:54

import djongo.models.fields
import mongodbapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongodbapp', '0002_vehiclerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('licence_plate_no', models.CharField(max_length=20)),
                ('rc_no', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Rickshaw', 'Rickshaw')], max_length=20)),
                ('aadharcard_number', models.CharField(max_length=12)),
                ('address', djongo.models.fields.EmbeddedField(model_container=mongodbapp.models.Address)),
                ('mobile_no', models.CharField(max_length=15)),
                ('chesis_no', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
    ]
