# Generated by Django 4.0.3 on 2024-11-01 07:35

from django.db import migrations, models
import djongo.models.fields
import mongodbapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mongodbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profiles', djongo.models.fields.ArrayField(model_container=mongodbapp.models.Profile)),
            ],
        ),
    ]
