# Generated by Django 4.1.13 on 2024-06-23 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_profile_aadharcard_no_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadharcard_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadharcard number must be exactly 12 characters long', regex='^.{12}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 characters long', regex='^.{10}$')]),
        ),
    ]
