# Generated by Django 4.0.3 on 2024-11-03 04:46

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mongodbapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echallan_main',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('Vehicle_No', models.CharField(max_length=255)),
                ('Owner_First_Name', models.CharField(max_length=255)),
                ('Owner_Last_Name', models.CharField(max_length=255)),
                ('Vehicle_Class', models.CharField(max_length=255)),
                ('Chassis_No', models.CharField(max_length=255)),
                ('Engine_No', models.CharField(max_length=255)),
                ('Make_Model', models.CharField(max_length=255)),
                ('Violation_Date', models.DateField()),
                ('Challan_Date', models.DateField()),
                ('Place_Of_Violation', models.TextField()),
                ('Driver_First_Name', models.CharField(max_length=255)),
                ('Driver_Last_Name', models.CharField(max_length=255)),
                ('Driving_license_No', models.CharField(max_length=255)),
                ('Driver_Contact_No', models.CharField(max_length=255)),
                ('Driver_Father_First_Name', models.CharField(max_length=255)),
                ('Driver_Father_Last_Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Echallan_main',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'Records',
            },
        ),
        migrations.CreateModel(
            name='MongoDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profiles', djongo.models.fields.ArrayField(model_container=mongodbapp.models.Profile)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('Aadhar_Number', models.CharField(max_length=12, unique=True)),
                ('Father_Aadhar_Number', models.CharField(blank=True, max_length=12)),
                ('Mother_Aadhar_Number', models.CharField(blank=True, max_length=12)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Postal_Code', models.CharField(max_length=20)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Enrollment_Date', models.DateField()),
                ('Last_Updated', models.DateField()),
                ('Is_Active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AadharCard',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Policy_No', models.CharField(max_length=100)),
                ('Provider', models.CharField(max_length=100)),
                ('Valid_Until', models.DateField()),
                ('Certificate_No', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Postal_Code', models.CharField(max_length=20)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Registration_Date', models.DateField()),
                ('Registration_Expiry', models.DateField()),
                ('Engine_No', models.CharField(max_length=12)),
                ('Chassis_No', models.CharField(max_length=12)),
                ('Engine_Capacity', models.IntegerField()),
                ('Seating_Capacity', models.IntegerField()),
                ('Color', models.CharField(max_length=10)),
                ('Year_of_Manufacture', models.DateField()),
                ('Make_Model', models.CharField(max_length=50)),
                ('Vehicle_Class', models.CharField(max_length=50)),
                ('Vehicle_Type', models.CharField(max_length=50)),
                ('Fuel_Type', models.CharField(max_length=50)),
                ('RC_No', models.CharField(max_length=20)),
                ('License_Plate_No', models.CharField(max_length=20)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Aadhar_Number', models.ForeignKey(db_column='Aadhar_Number', on_delete=django.db.models.deletion.CASCADE, to='mongodbapp.person', to_field='Aadhar_Number')),
            ],
            options={
                'db_table': 'Vehicle_Data',
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('Electricity_Bill_No', models.CharField(max_length=20, unique=True)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Owner_First_Name', models.CharField(max_length=100)),
                ('Owner_Last_Name', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Postal_Code', models.CharField(max_length=20)),
                ('Meter_Number', models.CharField(max_length=20)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Previous_Used_Unit', models.IntegerField()),
                ('Total_Used_Unit', models.IntegerField()),
                ('Rate_Per_Unit', models.FloatField()),
                ('Total_Bill_Amount', models.FloatField()),
                ('Late_Fee', models.FloatField()),
                ('Total_Amount_Due', models.FloatField()),
                ('Due_Date', models.DateField()),
                ('Is_Electricity_Bill_Paid', models.BooleanField(default=False)),
                ('Payment_Date', models.DateField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=20, null=True)),
                ('Aadhar_Number', models.ForeignKey(db_column='Aadhar_Number', on_delete=django.db.models.deletion.CASCADE, to='mongodbapp.person', to_field='Aadhar_Number')),
            ],
            options={
                'db_table': 'Electricity_Bill',
            },
        ),
    ]
